- hosts: web
  remote_user: root
  become: yes
  tasks:
    - name: Installed Apache
      yum:
        name: httpd
        state: installed
    - name: Start Apache Service
      service:
        name: httpd
        state: started
    - name: Removed Apache
      yum:
        name: httpd
        state: removed