- hosts: web
  remote_user: root
  become: yes
  tasks:
    - name: Install Packages
      shell: echo "installed httpd, git and nano"
      # notify: "install"

    - name: Start services
      shell: echo "Start services of httpd, git and nano"
      # notify: "Start Service"

    - name: Uninstall Packages
      shell: echo "uninstalled httpd, git and nano"
      notify: "uninstall"


  handlers:
    - name: Installed Apache
      yum:
        name: httpd
        state: installed
      listen: "install"

    - name: Installed Git
      yum:
        name: git
        state: installed
      listen: "install"

    - name: Installed nano
      yum:
        name: nano
        state: installed
      listen: "install"

    - name: Start Service
      service:
        name: httpd
        state: started

    - name: Removed Apache
      yum:
        name: httpd
        state: removed
      listen: "uninstall"

    - name: Removed ApaGitche
      yum:
        name: git
        state: removed
      listen: "uninstall"
    
    - name: Removed Nano
      yum:
        name: nano
        state: removed
      listen: "uninstall"