- hosts: localhost
  tasks:
    - name: Print name variable
      debug:
        msg: "{{ name }}"
    - name: populor courses
      debug:
        msg: "The most popular course is {{ courses [0] }}"
    - name: Print port variable
      debug:
        msg: "{{ http_port }}"