- hosts: localhost
  vars:
    name: My Name is Khan
    courses:
      - kubernetes
      - docker
      - ansible
      - terraform
      - jenkins
      - maven
      - gradle
      - sonarqube
      - artifactory
      - git
  tasks:
    - name: Print name variable
      debug:
        msg: "{{ name }}"
    - name: populor courses
      debug:
        msg: "The most popular course is {{ courses [0] }}"