- hosts: web
  remote_user: root
  become: yes
  tasks:
    - name: update all packages
      shell: "yum update -y"
    - name: Install Apache
      yum:
        name: httpd
        state: installed
    - name: Creating a file with content
      copy:
        dest: "/var/www/html/index.html"
      content: |
        <html>
        <h1> Hello </h1>
        </html>
    - name: Curl AWS
      shell:
        cmd: curl http://169.254.169.254/latest/meta-data/public-ipv4
      register: ip
    - debug: var=ip.stdout.lines
    