---
# handlers file for cleaner
- name: Removed Apache
  yum:
    name: httpd
    state: removed
  listen: "uninstall"

- name: Removed Git
  yum:
    name: git
    state: removed
  listen: "uninstall"

- name: Removed Nano
  yum:
    name: nano
    state: removed
  listen: "uninstall"